### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#1]
As a **developer** I can **setup a new Django project** so that **there is a base structure ready to implement necessary features**

# Tasks:
- [x] Install Django via the package manager
- [x] Create a new project named greener_gardens
- [x] Create the core app and add to the settings.py file
- [x] Create the env.py file to store and hide secret keys
- [x] Add env.py to the .gitignore file to ensure secret keys are hidden from deployed project
- [x] Create base.html page to act as a template for the site pages required
- [x] Create and organise the apps and files required for the project
