### ISSUE TITLE
USER STORY: Services Table

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#10]
Epic: #9 

# User Story
As a **user** I can **view the Services table** so that **I can see the different services offered by the business in an easy to understand format**

# Tasks:
- [ ] Build a table listing all available services
- [ ] Service Names included
- [ ] Service description included
- [ ] Reccommended frequency for service included
