### ISSUE TITLE
USER STORY: Flow Gallery

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#11]
Epic: #9 

# User Story: 
As a **user** I can **see images of gardens maintained by the business** so that **I can see the quality of their work prior to booking**

# Tasks:
- [ ] Create a flow gallery to display images of previous work completed by the company
- [ ] Ensure flow gallery is responsive on various devices and browsers
- [ ] Include buttons to allow users to click through the gallery images
