### ISSUE TITLE
USER STORY: UX/UI Design

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#14]
Epics: #3 , #9 #39 

## User Story
As a **user** I want **to have a good UX/UI experience when visiting the site** so that **I can have a positive interaction with the site and may be encouraged to register for an account and/or book a service**

## Tasks:
- [ ] Ensure colour scheme and fonts are consistent across all site pages
- [ ] Ensure the header () and footer () have been completed and are functioning on all pages
- [ ] Ensure all content is relavent to the site purpose
- [ ] Ensure all pages and features are responsive on various devices and browsers
- [ ] Ensure all links are functioning and correctly redirect to the corresponding pages.
