### ISSUE TITLE
EPIC: Project Submission

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#15]
# User Stories
- As a **developer** I can **write a README.md** so that **others can better understand the development process for this project** (#4 )
- As a **developer** I can **write a testing document** so that **all data relating to the testing of the project is in one place to allow others to better understand the testing of the project** (#5 )
- As a **developer** I can **deploy the final project to Heroku** so that **the site can be viewed by users and the project can be submitted for review as part of the Fullstack Developer Course with Code Institute** (#6 )

# Acceptance Criteria
- All functional requirements for the project work as intended
- The project has been deployed and the deployment is documented.
- The project must have been tested extensively with relevant documentation
- Sufficient documentation is included in the README.md file and is in English
- The project assessment criteria for the learning outcomes have been checked and achieved for the desired grade
- I am overall satisfied with the work.

# Tasks
- [ ] Completion of Epics: #3 #8 #9 
- [ ] All above User Story Tasks completed
- [ ] Review documentation and check for any spelling/grammer errors
- [ ] Ensure all links contained within the documentation are functioning as intended
