### ISSUE TITLE
EPIC: Project Set Up

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#16]
# User Stories
- As a **developer** I can **setup a new Django project** so that **there is a base structure ready to implement necessary features** (#1 )
- As a **developer** I can **deploy the project early on** so that **I can test the initial setup of the project to make sure this works, and continue testing throughout the development process** (#2 )

# Tasks:
- [ ] All User Story Tasks Completed
- [ ] Carry Out Testing and Code Validation
- [ ] Document testing results in TESTING.md
