### ISSUE TITLE
USER STORY: User Log In

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#19]
Epic:

# User Story
As a **user** I can **log into my personal account** so that **I can manage my own bookings and personal details**

# Tasks:
- [ ] Design Log In pop up
- [ ] Authentication of inputted details to either allow log in, or notify user of incorrect details
- [ ] Check all links function and redirect to the correct pages
