### ISSUE TITLE
USER STORY: Early Deployment

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#2]
As a **developer** I can **deploy the project early on** so that **I can test the initial setup of the project to make sure this works, and continue testing throughout the development process**

# Tasks:
- [x] Create a new app on Heroku
- [ ] Add all the secret keys to the config vars section
- [x] create a requirements.txt file
- [x] Create Procfile file 
- [ ] Set DEBUG to False for deployment
- [ ] Deploy to Heroku to test running of application
- [ ] When testing complete, set DEBUG to True to continue developing.
