### ISSUE TITLE
EPIC: Home Page

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#3]
# User Stories
- As a **user** I want to have **a good UX/UI experience when visiting the website** so that ** I can have a positive interaction with the site and may be encouraged to register for an account to book a service**
- As a **user** I can **see content about the business owner** so that **I can learn more about the owner and their experience in the industry**
- As a **developer** I can **create a base.html** so that **the template can be utilised to create other pages for the site**.

# Acceptance Criteria
- When visiting the website I expect the home page to be easy to navigate and visually appealing.
- When visiting the website on different devices I expect the site to be responsive and to adapt to the applicable screen size.
- When visiting the website I expect to see a button to register for/log in to an account.
- When visiting the website as a staff member I expect to see a button to log into a staff account

# Tasks:
- [ ] Design the layout of the home page
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
