### ISSUE TITLE
EPIC: Header

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#34]
# User Stories
- As a **user** I can **navigate through the website** so that **I can access different pages and sections of the site easily and efficiently**
- As a **user** I can **log into my personal account** so that **I can manage my own bookings and personal details**
- As a **logged in user** I can **log out of my account before leaving the site** so that **I can keep my account secure**
- As a **user** I can **reset a forgotten password** so that **I can regain access to my account**
- As a **user** I can **complete a registration form** so that **I can register for an online account and book in for services**
- As a **site owner** I can **see the company logo in the header** so that **users can identify the brand of the business, reinforcing brand recognition, and to allow navigation to the home page**

# Acceptance Criteria
- When I access the navigation bar, I expect it to be displayed at the top of the webpage at all times.
- When I click on any link contained within the header, I expect to be redirected to the corresponding page without delay and to be notified promptly if an issue occurs.
- When I view the navigation bar on different devices I can still navigate through the site without issue due to the responsive nature of the site.
- When I view the header, I expect any text or images to be designed with accessibility in mind

# Tasks:
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
