### ISSUE TITLE
USER STORY: Company Logo

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#37]
Epic: #34 

## User Story
As a **site owner** I can **see the company logo in the header** so that **users can identify the brand of the business, reinforcing brand recognition, and to allow navigation to the home page**

## Acceptance Criteria
- When accessing the site, I expect to see the Company Logo fixed on the far left of the header
- If the logo is clicked on by a user they should be redirected to the home page

## Tasks:
- [ ] Design logo and attach to project as a .png file.
- [ ] Fix logo to far left of the header before the navigation links
- [ ] Ensure logo is responsive to multiple devices and browsers
