### ISSUE TITLE
EPIC: Contact Page

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#38]
# User Stories
- As a **user** I can **see the business contact details and opening hours** so that **I can contact the business directly and during their opening hours with any booking/account queries** #26 
- As a **user** I can **view an interactive map** so that **I can see what locations are included in the catchment area for the business and if I can benefit at my own location** #27 

# Acceptance Criteria
- When accessing the contact page as a user I should see relevant contact details and opening hours for the business.
- As a user, when accessing the contact page, I should be able to interact with the map feature to see the boundary for the locations covered by the business.
- When accessing the contact page on various devices or browsers, the map feature and contact details should be responsive and functionality of the features should be uninterupted.

# Tasks:
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
