### ISSUE TITLE
EPIC: Booking System

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#39]
# User Stories
- As a **user** I can **receive a notification prior to booking cancellation ** so that **I can avoid cancelling a booking accidentally, and to be notified if a cancellation fee applies** #35 
- As a **logged in user** I can **view/edit/add/cancel bookings** so that **I can manage the bookings to keep in line with my personal calendar** #29 
- As a **user** I can **receive a notification after submitting a booking request** so that **I can see whether the submission was successful or not, and if not the reason why.** #24 
- As a **staff member** I can **view/accept/decline/edit bookings** so that **I can manage the business calendar and assist with customer booking queries** #22 
- As a **user** I want **to have a good UX/UI experience when visiting the site** so that **I can have a positive interaction with the site and may be encouraged to register for an account and/or book a service**

# Acceptance Criteria
- Criteria 1
- Criteria 2
- Criteria 3

# Tasks:
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
