### ISSUE TITLE
USER STORY: README.md

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#4]
Epic: #15 , #16 , #8 , #3 , #9 

# User Story
As a **developer** I can **write a README.md** so that **others can better understand the development process for this project**

# Acceptance Criteria
- UX section is to cover the 5 Planes of Website Design; Strategy, Scope, Structure, Skeleton, Surface
- Features section to include the following existing features for the project: #3 , Nav Bar, Footer, Contact Page, Services Page, User Account pages, Staff Account pages, Sign in page, Register page, sign out confirmation, bookings system
- Features section to include the following future features for the project:
- Testing section to include link to testing.md file (#5) 

# Tasks:
- [ ] Include Am I Responsive image for final project
- [ ] Complete Overview
- [ ] Complete UX section
- [ ] Complete Agile Methodology section
- [ ] Complete Features section
- [ ] Complete Responsive Layout and Design section
- [ ] Complete Tools Used section
- [ ] Complete Testing section
- [ ] Complete Deployment section
- [ ] Complete Credits section
- [ ] Complete Acknowledgements section
- [ ] Spell check and complete final review of README.md prior to final project submission
