### ISSUE TITLE
EPIC: User Account

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#40]
# User Stories
- As a **logged in user** I can **view/edit/delete my personal account details** so that **I can keep my details up to date or delete my account if the services are no longer required** #30 
- As a **user** I want **to have a good UX/UI experience when visiting the site** so that **I can have a positive interaction with the site and may be encouraged to register for an account and/or book a service**
- As a **logged in user** I can **select to opt-in to a newsletter subscription** so that **I can choose to stay up to date with the business, get early access to new services, and receive gardening tips** #31 
- As a **logged in user** I can **view/edit/add/cancel bookings** so that **I can manage the bookings to keep in line with my personal calendar**

# Acceptance Criteria
- Criteria 1
- Criteria 2
- Criteria 3

# Tasks:
- [ ] Design User Account Page
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
