### ISSUE TITLE
EPIC: Staff Account

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#41]
# User Story
- As a **site owner** I can **edit the calendar availability** so that **I can maintain control over the availability presented live to the users prior to booking**
- As a **staff member** I can **view/edit/delete user accounts** so that **I can maintain control over site access and user privileges, and keep user account details up to date**
- As a **staff member** I can **view/accept/decline/edit bookings** so that **I can manage the business calendar and assist with customer booking queries**

# Acceptance Criteria
- Criteria 1
- Criteria 2
- Criteria 3

# Tasks:
- [ ] Design Staff Account Page
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
