### ISSUE TITLE
USER STORY: TESTING.md

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#5]
As a **developer** I can **write a testing document** so that **all data relating to the testing of the project is in one place to allow others to better understand the testing of the project**

# Acceptance Criteria
- To include details of manual testing completed
- To include details of automatic testing completed
- To include evidence of code valiation completed for HTML, CSS, JavaScript and Python
- To include details of responsiveness testing completed on multiple devices
- To include details of testing completed on multiple browsers
- To include performance testing via Lighthouse
- To include details of user story completion

# Tasks:
- [ ] Complete Manual Testing
- [ ] Complete Automatic Testing
- [ ] Complete Code Validation
- [ ] Complete Responsiveness
- [ ] Complete Browser Compatibility
- [ ] Complete User Story Validation
