### ISSUE TITLE
USER STORY: Final Deployment

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#6]
As a **developer** I can **deploy the final project to Heroku** so that **the site can be viewed by users and the project can be submitted for review as part of the Fullstack Developer Course with Code Institute**

# Tasks:
- [ ] All commented out coding has been removed
- [ ] DEBUG has been set to false for deployment
- [ ] All functional requirements for the project have been completed
- [ ] Project deployed on Heroku
