### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#7]
As a **user** I can **navigate through the website** so that **I can access different pages and sections of the site easily and efficiently**

# Tasks:
- [ ] Design the Navigation Bar
- [ ] Ensure all links redirect to the correct pages of the site.
- [ ] Ensure the Navigation Bar is fully responsive on multiple devices and browsers
