### ISSUE TITLE
EPIC: Footer

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#8]
# User Stories
- As a **user** I can **scroll to view the footer** so that **I can access social media links quickly from any page on the site**
- As a **staff member** I can **access a staff only log in button** so that **I can log into the staff account to manage bookings and client accounts**

# Acceptance Criteria
- When I click on a social media link I expect to be redirected to the corresponding social media platform without delay or issues.
- When I click on the staff log in button I expect to be redirected to a staff only log in page
- When I am visiting the website, I expect the footer to be fixed to the bottom of the site page and not to overlay the site content.

# Tasks:
- [ ] Design the footer
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
