### ISSUE TITLE
EPIC: Services Page

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/greener-gardens#9]
# User Stories
- As a **user** I can **view the Services table** so that **I can see the different services offered by the business in an easy to understand format** (#10 )
- As a **user** I can **see images of gardens maintained by the business** so that **I can see the quality of their work prior to booking** (#11 )
- As a **site owner** I want to see **pricing listed** so that **I can offer transparency to my customers regarding the cost of the services available prior to booking** (#12 )

# Acceptance Criteria
- When I visit the Services page as a user I should see images in a flow gallery that can be clicked through with ease and without issues.
- When I visit the Services page as a user I should see a table of services with the applicable pricing correctly noted ordered from lowest cost to highest cost service.
- As a user, if I click on a text link within the Services page I should be redirected to the relevant page without delay or issues.

# Tasks:
- [ ] Design the layout of the services page.
- [ ] All User Story Tasks Completed
- [ ] All Acceptance Criteria Achieved
- [ ] Carry Out Testing and Code Validation
- [ ] Document features in README.md
- [ ] Document testing results in TESTING.md
